name: Deploy to EC2

on:
  push:
    branches:
      - master # Adjust branch name if necessary

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.17.0' # Adjust Node version as needed

      - name: Install dependencies
        run: npm install

      - name: Generate Migrations
        run: npm run migration:generate

      - name: Run migrations
        run: npm run migration:run

      - name: Run build
        run: npm run build # Ensure you have a build script in package.json

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }} # Your EC2 public IP
          username: ${{ secrets.EC2_USER }} # EC2 user, typically 'ubuntu' or 'ec2-user'
          key: ${{ secrets.EC2_SSH_KEY }} # Your private SSH key added as a secret
          port: 22
          script: |
            cd ~/findtute-server  # Adjust to your directory
            git pull origin master  # Pull latest changes
            npm install            # Install dependencies
            npm run build           # Build the app
            pm2 restart all         # Restart the server using PM2
